fix: branding for search page buttons
donategifts/donategifts pull request #157
Opened 2020-11-06 22:11 UTC by Enubia

added cdn links back as comments so that we can revert the static
serving in case this doesn't work

2020-11-07 17:31 UTC, gnorbsl commented
this might clash with my branch where I updated the scripts and added the map files, can we merge mine first and see if there are conflicts?

2020-11-07 18:30 UTC, Enubia commented
> this might clash with my branch where I updated the scripts and added the map files, can we merge mine first and see if there are conflicts?

sure

2020-11-07 20:16 UTC, Enubia commented
@gnorbsl ready for review

2020-11-07 21:01 UTC, gnorbsl requested changes

2020-11-07 21:01 UTC, gnorbsl commented on client/views/wishCards.ejs
> +                        %
your autoformat really fucks stuff up in the ejs files

2020-11-07 21:01 UTC, gnorbsl commented on client/views/wishCards.ejs
> +                        %
aside fromt that this reverts whats in master right now

2020-11-08 19:05 UTC, gnorbsl approved these changes

2020-11-08 19:05 UTC, merged