Typescript rewrite
donategifts/donategifts pull request #159
Opened 2020-11-07 12:42 UTC by Enubia

2020-11-07 14:01 UTC, gnorbsl requested changes

2020-11-07 14:01 UTC, gnorbsl commented on don-server/src/routes/routes.ts
> +        app.post('/api/users/sig-nup',
spelling error?

2020-11-07 14:03 UTC, Enubia commented on don-server/.prettierrc
> +	"printWidth": 100,
no since the prettier file is only used in the new directory

2020-11-07 14:05 UTC, Enubia commented on don-server/@types/index.d.ts
> +  export var io: any;
global type definitions for the typescript compiler

e.g. session does not exists on express, so we need a custom type for that
and io does not exists in the global scope per default

2020-11-07 14:07 UTC, Enubia commented on don-server/src/app.ts
> +global.io = connectSocket(app);
that will change anyways with the new tsoa setup

2020-11-07 16:14 UTC, Enubia commented on don-server/src/app.ts
> +global.io = connectSocket(app);
moved it for now :D

2020-11-07 17:30 UTC, Enubia commented on don-server/src/common/generic/ObjectId.ts
> +const isValidObjectId = <T>(str: string): str is TypeObjectId<T> => validateObjectId(str);
i will explain you and the other what that thing does in a short google meets call

2020-11-09 10:43 UTC, gnorbsl requested changes

2020-11-09 10:44 UTC, gnorbsl commented on don-server/package.json
> +    "test": "mocha --timeout 10000 --exit",
I think you wanted to use cross-env here to support windows users

2020-11-09 10:47 UTC, Enubia commented on .gitignore
> +config.env
yes it ignores them

2020-11-09 10:49 UTC, Enubia commented on don-server/package.json
> +    "test": "mocha --timeout 10000 --exit",
this test doesn't run right now and we need to rewrite it anyways once the tests are converted to typescript so this isn't an issue to worry about

2020-11-09 10:55 UTC, gnorbsl approved these changes

2020-11-09 10:55 UTC, merged