DEFECT: fix password reset#549
donategifts/donategifts pull request #589
Opened 2023-08-04 22:06 UTC by Zinminhtet21801

2023-08-04 22:20 UTC, Enubia requested changes

2023-08-04 22:20 UTC, Enubia commented on views/pages/passwordresetconfirmation.pug
> +                            console.log({response}, {textStatus})
please remove this log

2023-08-04 22:20 UTC, Enubia commented on views/pages/passwordresetconfirmation.pug
> +            });
please fix indentations

2023-08-05 01:52 UTC, Zinminhtet21801 commented
Done.

2023-08-05 09:56 UTC, Enubia approved these changes

2023-08-05 09:56 UTC, merged

2023-08-06 15:30 UTC, stacysealky commented
@Zinminhtet21801  @Enubia  have you guys tested this in https://donate-gifts-test.fly.dev/?

2023-08-06 15:44 UTC, Enubia commented
> @Zinminhtet21801  @Enubia  have you guys tested this in https://donate-gifts-test.fly.dev/? 

No not yet but it's deployed